export const metadata = {
    title: "Serena | Contacto",
    description: "Generated by create next app",
  };


function Contacto() {
    return (
        <section>
        <h1 className="mt-5 mb-3 font-bold text-orangeMedium text-3xl text-center">
            Contáctanos que nos gusta pedir proyectos gratis!
        </h1>
        <div className="flex justify-center items-center">
            <form className="bg-creamBg mx-auto flex gap-10 flex-col">
                <div>
                <input className="bg-white" type="text" />
                <input className="bg-white" type="text" />
                </div>
                <div>
                <input className="bg-white" type="email" />
                <input className="bg-white" type="text" />
                </div>
                <textarea className="w-full" name="" id=""></textarea>
                <button className="bg-orangeMedium text-white font-medium" type="submit">Enviar</button>
            </form>
        </div>
        </section>
    );
}

export default Contacto;