export default function TerminosPage() {
    return (
        <main className="p-8">
        <div className="mx-auto">
            <h1 className="text-orange-600 font-semibold text-center text-2xl mb-4">Términos y condiciones</h1>
            <h3 className="text-orangeMedium text-xl mb-4 font-semibold">Nuestros precios incluyen:</h3>
            <p>Los servicios que se especifican en cada itinerario. En los casos en que se incluye transporte este se brinda de acuerdo al itinerario y al medio elegido. Alojamiento en los hoteles previstos y/o similares en categoría ocupando habitación y/o departamento con baño privado. Comidas de acuerdo al régimen elegido. Visitas y excursiones mencionadas.</p>
            <h3 className="text-orangeMedium text-xl my-4 font-semibold">Nuestros precios no incluyen:</h3>
            <p>Bebidas y/o gastos extras de ningún tipo, gastos de índole personal, tasas locales de turismo yo aeropuertos, exceso de equipaje, llamadas telefónicas, gastos de comida yo refrigerio en las paradas en ruta, impuestos yo aranceles aduaneros yo migraciones, propinas y/u otro gasto especificado. Las excursiones opcionales que figuran en los diversos itinerarios.</p>
            <h4 className="text-orangeMedium text-xl my-4 font-semibold">Tarifas</h4>
            <p>Todos los precios indicados en nuestros folletos yo tarifarios yo publicaciones están sujetos a modificaciones sin previo aviso. 8 pasajero se compromete a abonar la diferencia resultante antes de iniciar el tour. Todos los tours deben ser abonados en su totalidad antes de que estos comiencen. </p>
            <h4 className="text-orangeMedium text-xl my-4 font-semibold">Precios congelados</h4>
            <p>En los casos expresamente indicados el precio quedara fijo e inamovible mediante el pago total del viaje al momento de efectuar la reserva. La fata de pago en termino de las facilidades acordadas hará perder automáticamente el beneficio de la congelación del precio. Sobre los precios La Empresa reserva su comisión como Operador del Viaje.</p>
            <h5 className="text-orangeMedium text-xl my-4 font-semibold">Alteraciones</h5>
            <p>El/Los Operador Responsable se reserva el derecho de alterar el horario, el itinerario y las excursiones locales por razones de programación o para su mejor desarrollo sin alterar la duración del tour. Si el viaje tuviera que prolongarse mas allá de los términos fijados por casos no imputables a La Empresa, ésta deslinda expresamente la responsabilidad de seguir brindando el alojamiento en el hotel previsto, siendo los pagos que se originen por cuenta del pasajero. Si la salida del viaje debiera postergarse por causas no imputables a La Empresa tales como huelgas, catástrofes naturales, etc., esta se reserva el derecho a cancelar el viaje o acortar la duración del mismo y modificar el itinerario en función de las reservas de servicios efectuados, quedando solamente obligada a reintegrar los importes correspondientes a los servicios no brindados. B Organizador podrá anular cualquier tour justificadamente, cuando ocurriera cualquiera de las siguientes causas: a) causas de fuerza mayor, b) alteración de tarifas y/o costos de servicios o tipo de cambio que obligue a un momento del viaje en proporción mayor a un 20%, c) cuando no se halla alcanzado un numero suficiente de pasajeros. En tal caso La Empresa solo queda obligada a reintegrar los importes percibidos al valor de la tarifa vigente al dia de la cancelación, previa deducción de un 10% del valor total en concepto de gastos de gestión y reserva</p>
            <h5 className="text-orangeMedium text-xl my-4 font-semibold">Inscripciones y anulaciones</h5>
            <p>Las inscripciones serán recibidas en firme mediarte el pago del 30% del valor total del tour. El saldo restante deberá hacerse efectivo 15 idas antes de la partida. En caso que el pasajero inscripto desista por cualquier causa del viajes, El Operador reembolsara al cliente la suma recibida previa deducción de un 10% del valor total del viaje en concepto de gastos de gestión y reservas, si la cancelación se efectúa con una anticipación de mas de 30 días a la fecha de partida. A partir del los 30 días anteriores a la partida y hasta 15 días antes, el cargo de cancelación será del 60%. A partir de los 14 días de la fecha de partida el cargo de cancelación será del 100%. La fecha de cancelación será establecida el día que La Empresa reciba por medio fehaciente la comunicación del pasajero en tal sentido.</p>
            <h5 className="text-orangeMedium text-xl my-4 font-semibold">Cambios de fecha de partida</h5>
            <p>Existiendo la posibilidad por parte del Operador, los cambios de fecha de partida tendrán los siguientes cargos: hasta 30 días antes la fecha de partida originaria el cargo será del 10% sobre el valor total del tour, desde 29 días y hasta 15 días antes de la fecha de partida originaria, el cargo será del 20% sobre el valor total del tour, desde 14 días y hasta 7 días antes de la fecha de partida originaria, el cargo será del 30% sobre el valor total del tour, desde 6 días y hasta el dia de partida originaria, el cargo de cancelación quedara a consideración del Operador. Todos los cambios de la fecha de partida se deberán realizar en forma fehaciente con el Operador, recién allí será considerada la anticipación con que se solicita el cambio.</p>
            <h6 className="text-orangeMedium text-xl my-4 font-semibold">Reembolsos</h6>
            <p>Todas las reclamaciones de reembolsos deberán ser dirigidas por escrito a La Empresa inscriptora dentro de los 60 días siguientes de la finalización del tour, debiendo los reembolsos efectuarse en esta misma agencia. No se reembolsara cantidad alguna por servicios no utilizados voluntariamente por el pasajero, Los reembolsos se verificaran únicamente de acuerdo al costo de los servicios prestados por terceros, o utilizados o cancelados. Los reembolsos se ajustaran a lo dispuesto por el decreto 2181/72 art.21.</p>
            <h6 className="text-orangeMedium text-xl my-4 font-semibold">Equipajes</h6>
            <p>El Operador transportara una maleta de tamaño normal que no exceda los 10 Kg y una pieza de mano por persona. B equipaje y los demás efectos personales del viajero no so objeto del contrato de transporte, extendiéndose a todos los efectos que este siempre conserva consigo, cualquiera sea esta la parte del vehículo que sean colocados y que son transportados por el propio viajero, por su cuenta y riesgo sin que el Operador quede obligado a responder contractualmente de la perdida o daño que los mismos pudieran sufrir por cualquier causa durante el viaje. Quien desee un seguro que lo cubre ampliamente podrá suscribir una póliza de esta índole en nuestras oficinas por el tiempo y monto que le interese.</p>
            <h6 className="text-orangeMedium text-xl my-4 font-semibold">Responsabilidad</h6>
            <p>El Operador no se responsabiliza por daños y perjuicios que pudieran sufrir los pasajeros y en los bienes cualquiera sea la causa que los origine. Operador declara explícitamente que actúa como intermediario entre los viajeros y las entidades o personas llamadas a facilitar los servicios que se indican en los itinerarios, o sea, Empresa de Transporte, Restaurantes, Hoteles, etc. Por consiguiente declina toda responsabilidad por deficiencias en cualquiera de los servicios prestados, así personas que efectúen el viaje por su mediación, así como el equipaje y demás objetos de su propiedad, por malas condiciones climáticas y/o atmosféricas, decisiones de los gobiernos, catástrofes naturales, huelgas y demás sucesos que pudieran ocurrir fuera del control del mismo. El billete del pasaje constituirá el único compromiso entre la Compañía de Transporte y el pasajero. El Operador deslinda toda responsabilidad por la tramitación y vigencia de la documentación del pasajero y los inconvenientes que por tal causa pudiera sufrir el mismo a cuyo cargo serán los gastos que corresponda por demora y abandono del tour motivados en falta a deficiencia de la documentación necesaria.</p>
            <h3 className="text-orangeMedium text-xl my-4 font-semibold">Derecho de conducta</h3>
            <p>El Operador se reserva el derecho de hacer abonar el tour, recurriendo a la fuerza publica si fuera necesario, a todo pasajero que por su modo de expresarse, comportarse o estado de salud, a solo juicio del guía, se convirtiese en molestia para los pasajeros o en impedimento para el buen desarrollo de la excursión en dicho caso la Empresa solo quedara obligada a reintegrar al pasajero separado del tour el importe equivalente de los servicios que restan brindar. Este reembolso será efectuado a pedido del pasajero en la Empresa inscriptora.</p>
            <h3 className="text-orangeMedium text-xl my-4 font-semibold">Conocimiento de condiciones</h3>
            <p>A efectuar la compra de uno de los tours, queda automáticamente sentado que el cliente se notifica que acepta las presentes condiciones generales.</p>
        </div>
      </main>
    );
  };
  