import {Montserrat, Moon_Dance, Assistant} from "next/font/google";
import localfont from "next/font/local";
import "./globals.css";
import Header from "@/app/components/ui/Header";
import HeaderMobile from "@/app/components/HeaderMobile"
import Footer from "@components/Footer"
import MenuContextProvider from "@/app/context/MenuContext";
import ProductsContextProvider from "@/app/context/ProductsContext";

export const BOOMSTER = localfont({
  src: [
    {
      path: "./fonts/BOOMSTER.otf",
      weight: "400",
    },
  ],
})

export const moonDance = Moon_Dance({
  subsets: ["latin"],
  weight: "400"
});

export const assistant = Assistant({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <title>Serena | Viajes y Turismo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </head>
      <body
        className={`${montserrat.className} bg-whiteBg font-medium antialiased`}
      >
        <ProductsContextProvider>

        <MenuContextProvider>
        <HeaderMobile />
        <Header />
        {children}
        <Footer />
        </MenuContextProvider>

        </ProductsContextProvider>
      </body>
    </html>
  );
}
