import type { Metadata } from "next";
import {Montserrat, Moon_Dance, Assistant} from "next/font/google";
import localfont from "next/font/local";
import "./globals.css";
import Header from "@/app/components/ui/Header";
import HeaderMobile from "@/app/components/HeaderMobile"
import Footer from "@components/Footer"
import MenuContextProvider from "@/app/context/MenuContext";

// MONTSERRAT ✅
// BOOMSTER ✅
// ASSISTANT
// MOON DANCE

export const BOOMSTER = localfont({
  src: [
    {
      path: "./fonts/BOOMSTER.otf",
      weight: "400",
    },
  ],
})

export const moonDance = Moon_Dance({
  subsets: ["latin"],
  weight: "400"
});

export const assistant = Assistant({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Serena | Viajes y Turismo",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",

  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${montserrat.className} bg-whiteBg font-medium antialiased`}
      >
        <MenuContextProvider>

        <HeaderMobile />
        <Header />
        {children}
        <Footer />
        </MenuContextProvider>
      </body>
    </html>
  );
}
