import './admin.css'

export const metadata = {
    title: "Serena | Login",
    description: "Generated by create next app",
  };

export default function AdminPage() {
    return (
        <section className="">
            <div className='bg-creamBg background gap-3 my-10 p-12 flex flex-col items-center justify-center mx-auto w-[500px]'>  
                <div className='flex flex-col items-center gap-2 justify-center'>
                    <img 
                    className='w-32' 
                    src="logo.png" 
                    alt="logo" />
                    <p className='font-extrabold text-xl'>Inicio de sesión</p>
                </div>
                <form className='flex flex-col w-full gap-5 justify-center items-center' action="">
                    <input placeholder='Usuario' className='px-5 py-2 shadow-sm w-full h-12 rounded-xl mx-20' type="text" />
                    <input placeholder='Contraseña' className='px-5 py-2 shadow-sm w-full h-12 rounded-xl mx-20' type="text" />
                    <button className='text-center bg-orangeMedium shadow-xl text-white rounded-xl w-full mx-auto p-2'>Ingresar</button>
                </form>
           </div>
        </section>
    )
}