
import Bus from './Bus.css'
import FormBus from '@components/FormBus'

export const metadata = {
    title: "Serena | Pasajes en Bus",
    description: "Generated by create next app",
  };

function BusPage() {
    return (
        <section id='background' className=" flex justify-center md:justify-start background px-20 py-20">
            <FormBus />
        </section>
    );
}

export default BusPage;